server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    com.ksy.exam.chat_exmple: debug